### ISSUE TITLE
Enable l10n for site

### ISSUE THREAD

**Issue by sknorr** [openSUSE/doc-o-o#10]
We'd need a new Weblate project for this, but I can only add new components.

**Comment by sknorr** [comment]
We have a Weblate setup thanks to sbrabec now. However, the remaining issue to be resolved is that the opensuse-i18n user cannot be added to the repo, so Weblate can't commit into the repo.

**Comment by guoyunhe** [comment]
You need to add some web hooks to GitHub repo settings. Here is an example:

![image](https://user-images.githubusercontent.com/5836790/108472254-77dd9200-72c7-11eb-9097-dfca7f09707d.png)

**Comment by sknorr** [comment]
@guoyunhe We have that. However, Weblate can't push yet because I could not add the @opensuse-i18n user to the repo

**Comment by sknorr** [comment]
Stanislav has provided a workaround -- adding a GitHub group that includes the necessary blocked user somehow works just fine.

Closing.
