### ISSUE TITLE
Unify website repo names

### ISSUE THREAD

**Issue by guoyunhe** [openSUSE/doc-o-o#6]
We have:
- www-o-o
- doc.o.o
- news-o-o
- wiki
- paste

Would be better to have all repos in same name patrern:
- www-o-o
- doc-o-o
- news-o-o
- wiki-o-o ( wiki.opensuse.org redirects to en.opensuse.org )
- paste-o-o

Or:
- www
- doc
- news
- wiki
- paste

CC @hellcp

**Comment by hellcp** [comment]
I have been naming repos `*-o-o` for this reason

**Comment by guoyunhe** [comment]
@sknorr can you rename this repo to doc-o-o?

**Comment by sknorr** [comment]
Done.
