### ISSUE TITLE
Mobile Usability Issues reported by Google Search Console

### ISSUE THREAD

**Issue by fsundermeyer** [openSUSE/doc-o-o#7]
Search Console

Mobile Usability issues detected on http://doc.opensuse.org/

To the owner of http://doc.opensuse.org/:

Search Console has identified that your site is affected by 3 Mobile  
Usability issues:

* Viewport not set
* Clickable elements too close together
* Text too small to read

We recommend that you fix these issues when possible to enable the best  
experience and coverage in Google Search.

**Comment by guoyunhe** [comment]
Will be fixed by #5

**Comment by sknorr** [comment]
That is for some of the old content. Google gives me this as an example URL: http://doc.opensuse.org/projects/YaST/SLES10SP1/tdg/id_big_architecture.html . While that is sad, the only solution would be to delete the old libzypp/YaST/... documentation from the server entirely.

I think none of these are issues on the homepage or the Leap content pages.

**Comment by sknorr** [comment]
Let's just close this out. Old content exists and will continue to exist but it's not reasonable to rebuild it.
